### ISSUE TITLE
Adapt cheshire Dockerfile to pudl-scrapers

### ISSUE THREAD

**Issue by zaneselvans** [catalyst-cooperative/pudl-archiver#13]
We have a Dockerfile which uses mambaforge in [the cheshire template repo](https://github.com/catalyst-cooperative/cheshire). Adapt it to containerizing the `pudl-scrapers` and running `scrape_everything.sh`

**Comment by zschira** [comment]
Closing see the new [archiver](https://github.com/catalyst-cooperative/pudl-archiver) repo

**Comment by jdangerx** [comment]
@zaneselvans is this still relevant in the Archiver Era?

**Comment by zaneselvans** [comment]
I don't think so
