### ISSUE TITLE
Archive FERC EQR pre-2013

### ISSUE THREAD

**Issue by zschira** [catalyst-cooperative/pudl-archiver#149]
The existing EQR archiver only archives data from 2013-present. There is commented out code for archiving earlier years of data, but as of now it does not work. This is because these years of data is only available on an FTP server that has a global 3 user limit (see [here](https://www.ferc.gov/download-database#main-content) for more info). As a workaround to this limit, the commented out code will attempt to ping the ftp server until it gets a successful response, then try to download the data. So far in testing, however, the archiver has not been able to successfully interface with the server even when running all night trying to ping it.

**Comment by jdangerx** [comment]
I think that's a good direction for when we finally take on all of EQR. Closing for now.
