### ISSUE TITLE
Remove `--dry-run` option in favor of `--auto-publish`

### ISSUE THREAD

**Issue by jdangerx** [catalyst-cooperative/pudl-archiver#208]
Both `--dry-run` and `--auto-publish` (which defaults to `False`) are trying to make it so we can check the output before accidentally publishing some bogus version of our data.

However, `--dry-run` doesn't provide a faithful simulation of what it would be like to run the archiver, because it skips all uploads to Zenodo, which means the generated `datapackage.json` is incorrect, which then means that our validation checks don't behave as expected, and now half the code we wanted to verify isn't really running in the way it would "in production."

That is all solved with `--auto-publish`, which just skips the final publishing step. The downside is that `--dry-run` is faster because we don't upload to Zenodo.

We should remove `--dry-run`.

```[tasklist]
## Success criteria
- [ ] `--dry-run` no longer a setting that we use
- [ ] docs reflect new usage pattern
- [ ] all references to `--dry-run` removed from codebase
```

**Comment by siwamsingh** [comment]
I read the description.
Correct me if I am wrong but from what I understood we just have to do is to replace "--dry-run" with "--auto-publish" right ?

**Comment by jdangerx** [comment]
Hi Siwam! Thanks for taking a look.

Right now we already have both a `--dry-run` and an `--auto-publish` option. I think the task here is to just take out the `--dry-run` option and all references to it. I don't think there's a need to touch `--auto-publish`. Does that sound like something you'd like to take on?

**Comment by siwamsingh** [comment]
Thank you for your response, @jdangerx.
I now understand the issue. I would like the opportunity to contribute to this project. I would be very grateful if you could assign this issue to me.😊

**Comment by jdangerx** [comment]
Sure thing, thanks for offering to help!

**Comment by siwamsingh** [comment]
Thanks for assigning the task to me .
i removed the part containing "--dry-run" from cli.py and also removed it from README.md.
<img width="583" alt="Screenshot 2023-12-12 111406" src="https://github.com/catalyst-cooperative/pudl-archiver/assets/140843501/333d3cb2-b90b-46d5-8e75-4b91a813fa12">

**Comment by jdangerx** [comment]
For posterity - this issue **_is_** still open and available for development. It requires removing the `--dry-run` flag and also any places in the code where we use the value of that flag.

**Comment by samleonard** [comment]
Hi @jdangerx! I just made a [PR](https://github.com/catalyst-cooperative/pudl-archiver/pull/326) for this. Please let me know what next steps I should take.
