### ISSUE TITLE
Ensure continuous data availability for CEMS and 860M archives

### ISSUE THREAD

**Issue by jdangerx** [catalyst-cooperative/pudl-archiver#218]
CEMS data now includes 1 file for each quarter (~110 files). One useful additional dataset specific validation to add to `DatasetSpecificValidation` would be to check that that there are no quarters of missing data (that each quarter of CEMS data from the first partition to the last is present). This check could be extended to 860M data as well, to ensure that there are no missing months of data.
```[tasklist]
### Tasks
- [ ] Add validation for continuous CEMS
- [ ] Add validation for continuous EIA 860m
```

**Comment by aesharpe** [comment]
See #214 for success conditions
