### ISSUE TITLE
Add creation of a Github issue to the `run-archiver.yml` workflow

### ISSUE THREAD

**Issue by e-belfer** [catalyst-cooperative/pudl-archiver#258]
When the `run-archiver.yml` workflow runs monthly, it creates a Slack notification. To make sure we actually publish the draft archives created, it should also result in the creation of a Github issue. Ideally this issue will have a short description of what review entails, and a tasklist with links to the draft archives. A more minimal version would just be to include the links in the issue.

**Comment by zaneselvans** [comment]
It would be great if it would automatically assign the issue to @catalyst-cooperative/inframundo as well.

**Comment by e-belfer** [comment]
Subsumed and duplicated by #346, closing.
