### ISSUE TITLE
phmsagas validation failure

### ISSUE THREAD

**Issue by zschira** [catalyst-cooperative/pudl-archiver#337]
The phmsagas archiver had the following validation failure: 

> The following files would be deleted by new archive version: {'phmsagas-gas_distribution_2010_present.zip', 'phmsagas-gas_distribution_1970_2003.zip', 'phmsagas-gas_transmission_gathering_1970_2000.zip', 'phmsagas-gas_transmission_gathering_2010_present.zip', 'phmsagas-gas_distribution_2004_2009.zip', 'phmsagas-underground_natural_gas_storage_2017_present.zip', 'phmsagas-liquefied_natural_gas_2010_present.zip', 'phmsagas-hazardous_liquid_2010_present.zip', 'phmsagas-hazardous_liquid_2004_2009.zip', 'phmsagas-reporting_regulated_gas_gathering_2022_present.zip', 'phmsagas-gas_transmission_gathering_2001_2009.zip'}".

Seems bad to be losing so many files. Was there a change in naming conventions or structure?

**Comment by zaneselvans** [comment]
Usually when we lose a ton of files like this it means that the archiver wasn't actually able to download the files at all.

But I think what has happened here is that the file naming was changed in #320 switching from using a dash to an underscore.

**Comment by e-belfer** [comment]
@zaneselvans is correct, I made this change because it was annoying me, and completely forgot to tell anyone else. Closing this issue.
