### ISSUE TITLE
nrelatb - Deleted record error

### ISSUE THREAD

**Issue by zschira** [catalyst-cooperative/pudl-archiver#339]
The latest run of the nrelatb archiver ran into an error about the record being deleted when trying to get the latest version of the deposition from zenodo. Was a version deleted at some point that we're trying to retrieve?

**Comment by zaneselvans** [comment]
We aren't able to delete records, and would have had to ask Zenodo to do it manually, and I don't think that happened.  My guess is this is another instance of the fake deleted DOI thing that happened with the AEO last month.

**Comment by e-belfer** [comment]
Still an issue on June 1, I emailed to ask about this and the EIA AEO which both have this error today. Will update when fixed.

**Comment by e-belfer** [comment]
Still no response, emailed for a third time today.

**Comment by zaneselvans** [comment]
Well, [the new ATB data is out](https://www.nrel.gov/news/program/2024/plug-into-newly-released-2024-us-electricity-sector-data.html)! Hopefully we can get them to fix this before July 1st.

**Comment by e-belfer** [comment]
Fixed by pointing the DOI temporarily at the last record, running the update, and then reverting it. The concept DOI link now seems to be [working as expected](https://zenodo.org/api/records/12609821). [New archive here](https://zenodo.org/records/12609821).
