### ISSUE TITLE
Update FERC archivers to handle multiple taxonomies in one year

### ISSUE THREAD

**Issue by jdangerx** [catalyst-cooperative/pudl-archiver#349]
### Overview

FERC form 1 was reported using multiple taxonomies in 2023:

* 2023 Q1 through Q3 used a `2023-04-01` taxonomy
* 2023 Q4 used a `2023-11-01` taxonomy, which had some fields slightly renamed to address ambiguity introduced in the `2023-04-01` update. See catalyst-cooperative/pudl#3544 for details.

This means that in the extraction, we need to use different taxonomies per file. Which also means that we should *track* which taxonomy to use in the metadata.

### Success Criteria
* [ ] filename is in metadata (#178 )
* [ ] taxonomy version is also in metadata
* [ ] taxonomy archives include full date instead of just year

```[tasklist]
### Next steps
* [ ] #178 
* [ ] open the XML files, look for the taxonomy links, and parse out a version from them
* [ ] update taxonomy archive filenames
```

**Comment by zaneselvans** [comment]
I think this should probably get bumped to High or Urgent priority so that we can unblock work on the new year of FERC Form 1 data.
