### ISSUE TITLE
Investigate partition "changes" when updating FERC archives

### ISSUE THREAD

**Issue by e-belfer** [catalyst-cooperative/pudl-archiver#399]
In #398 and the corresponding archive [run](https://github.com/catalyst-cooperative/pudl-archiver/actions/runs/10194817765), every FERC XBRL archive was marked as having its partition changed, even though the links are identical to what they were. In September, if this happens again, we should investigate it. This is a two-fold task:

- Investigate the "changed" partitions
- Sort the values in the taxonomies_zip, to prevent them from changing each month by order.

**Comment by zschira** [comment]
I've opened a PR to attempt to address this issue. See #433 for more details.

**Comment by zschira** [comment]
Closing. Partition changes are fixed, but there's still issues with XBRL zip file changes which will be tracked in #471.
