### ISSUE TITLE
Rewrite EPA CEMS archiver to use API

### ISSUE THREAD

**Issue by zaneselvans** [catalyst-cooperative/pudl-archiver#68]
At some point in the last few months, EPA seems to have removed the bulk CSV files containing hourly emissions data from their site, and are now exclusively making the data available through an API.

* The [old URL](https://gaftp.epa.gov/DMDnLoad/emissions/hourly/monthly) now gives a 404, though a lot of other data remains on the server. [Top level index](https://gaftp.epa.gov/)
* [Emissions data API Documentation](https://www.epa.gov/airmarkets/cam-api-portal#/swagger/emissions-mgmt)
* [GitHub repo with example usage](https://github.com/USEPA/cam-api-examples) 

Looking at their [example bulk Python download script](https://github.com/USEPA/cam-api-examples/blob/main/Python/bulk_data_api_demo.py) it seems like it's possible to download CSVs from an s3 bucket. Hopefully they're not too different from the CSVs we were previously downloading directly from EPA!

Note that this API replaces .zip files with one .csv file for each state-year, so we will also need to adjust the extraction step in `pudl` to match the new data format.

**Comment by zaneselvans** [comment]
@bendnorman as you work on the gridstatus data archiving maybe keep this issue in mind too for application of similar patterns.

**Comment by ggurjar333** [comment]
@zaneselvans Can I take this?
