### ISSUE TITLE
Running archiver with `--dry-run` leaves an unpublished draft

### ISSUE THREAD

**Issue by zaneselvans** [catalyst-cooperative/pudl-archiver#75]
The `--dry-run` option isn't quite as dry as I thought it would be.
* When run on an existing dataset, a draft deposition is created (apparently based on the most recently published version) and left unpublished on Zenodo. I think doing a "dry run" should have no effect on Zenodo, and only communicate what would have been done if a real run had been requested.
* When run in combination with `--initialize` an empty draft deposition is created and left unpublished.

**Comment by jdangerx** [comment]
I think the scope here is:
- [ ] no drafts left behind after a dry-run

The next steps are:
- [ ] test to see if this is already fixed by #69 
- [ ] if not, delete the draft after we say "Dry run, aborting" in `orchestrator.py`

**Comment by e-belfer** [comment]
We've removed `--dry-run` as a flag in #326, so I'm closing this issue.
