### ISSUE TITLE
Add all new archives to the Catalyst Cooperative community

### ISSUE THREAD

**Issue by zaneselvans** [catalyst-cooperative/pudl-archiver#76]
We have a "community" on Zenodo that collects all of our published archives together at: https://zenodo.org/communities/catalyst-cooperative/

Currently new archives have to be added to the community manually, but we should automate the process so all of our data can be found more easily by users.

Unfortunately Zenodo currently only allows a single community curator, and the account associated with it belongs to @zaneselvans rather than the PUDL Bot which owns all of the datastore archives, so Zane will have to approve requests to join the community. This issue will be fixed in a future version of the Zenodo backend.

**Comment by e-belfer** [comment]
Should we incorporate this into our 2022 new data integration blitz? What needs to be done here to finish out this issue @zaneselvans ?

**Comment by zaneselvans** [comment]
I think that there should be some way to use the Zenodo API to add a new record to the `catalyst-cooperative` community when it's created or right after it's been created.  Then I'll have to go approve it since I own the community and there's still no way to share or transfer curation duties.  I think @zschira is most familiar with the Zenodo API at this point.

**Comment by e-belfer** [comment]
The Zenodo migration to InvenioRDM has changed the way that communities work, making this addition simpler from the API. I'm picking this issue back up, should be relatively trivial to add communities to our default `DepositionMetadata`

**Comment by zaneselvans** [comment]
Oh great, this is such a hassle right now. Thank you for picking it up!

**Comment by e-belfer** [comment]
In the current iteration of Zenodo, it's not possible to add a record to a community using the API and then manually approve it using the GUI - records are only adding through the GUI or when the `--auto-publish` flag forces direct publication through the API. Since this doesn't address our needs right now I am closing this issue but will merge #202 with just the `--refresh-metadata` functionality.
