### ISSUE TITLE
Archiver no longer works with most recent `pudl@dev`

### ISSUE THREAD

**Issue by jdangerx** [catalyst-cooperative/pudl-archiver#90]
```[tasklist]
### Scope
- [ ] pin archiver to `main` instead of `dev`
- [ ] archivers run again
```

**Comment by e-belfer** [comment]
@zaneselvans I'm happy to try to work on this, but I'm wondering if you resolved this by pinning to [the pre-dag](https://github.com/catalyst-cooperative/pudl-archiver/commit/b4ec2b2134fd482259e1ce09fc3a5864963e5ca7), or if is this ticket scope is still current?

**Comment by e-belfer** [comment]
@jdangerx Closing this issue, think it's been addressed.
